### ISSUE TITLE
"invalid escape sequence" error for regex

### ISSUE THREAD

**Issue by phlavenk** [JunoLab/Weave.jl#223]
Example of Weave parsing error inside function's help string leading to
 Error: Weaving failed.
│   error = Base.Meta.ParseError("invalid escape sequence")
└ @ Main none:1
`test.jmd:`

```
example of error
```julia
"""
  calculate_snr(regex, label)
regex similar to `(r"SNR_ETD_(?<Ip>\d+)pA_sig_noise_*"` capture probe current Ip in pA
"""
function calculate_snr(data_dir, reg::Regex)
  data_dir
end
 ```
```
Is it a Julia problem or weave parsing problem?

**Comment by devmotion** [comment]
If you paste your code into the Julia REPL you'll get the same error message, so it's not a Weave parsing problem.

As mentioned in [the documentation of Documenter.jl](https://juliadocs.github.io/Documenter.jl/stable/man/latex/), some characters such as `$` and `\` are treated differently in doc strings. Instead of your example you should write
```julia
"""
    calculate_snr(regex, label)

regex similar to `(r"SNR_ETD_(?<Ip>\\d+)pA_sig_noise_*"` capture probe current Ip in pA
"""
function calculate_snr(data_dir, reg::Regex)
    data_dir
end
```
or
```julia
@doc raw"""
    calculate_snr(regex, label)

regex similar to `(r"SNR_ETD_(?<Ip>\d+)pA_sig_noise_*"` capture probe current Ip in pA
"""
function calculate_snr(data_dir, reg::Regex)
    data_dir
end
```

Note that I used a four-space indent in the line with the function signature at the top of the documentation to ensure that it is printed as Julia code. You can find more conventions in the [documentation](https://docs.julialang.org/en/latest/manual/documentation/#Documentation-1).

**Comment by tlnagy** [comment]
Thanks @devmotion for your answer, please open a new bug if you run into any other issues

**Comment by phlavenk** [comment]
Sorry for such long delay in my response. Thank you for your quick and precise answer.
